### ISSUE TITLE
v3.4 Checklist

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1826]
- [ ] new [`createGlobalStyle` API](https://github.com/styled-components/styled-components/pull/1807)
- [x] last set of TS [`withComponent` typing fixes](https://github.com/styled-components/styled-components/pull/1739)
- [x] [preact prop support](https://github.com/styled-components/styled-components/pull/1823)
- [x] [update rollup](https://github.com/styled-components/styled-components/pull/1824)
-  ~~a fix for this [TS issue around CSS mixins](https://github.com/styled-components/styled-components/issues/1821)~~ not solvable without TS 2.9+

**Comment by probablyup** [comment]
I'm going to go ahead and release 3.4 tomorrow without the new API.

**Comment by probablyup** [comment]
3.4.0 is out
