### ISSUE TITLE
5.0 Roadmap

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1934]
Test it out:

```shell
npm install styled-components@beta react@^16.8 react-dom@^16.8 react-is@^16.8
```

_5.0 milestone_

- [x] ~~rewrite stylesheet + tag classes for the needs of today (#2522)~~
- [x] ~~move react-is to peer dependencies (https://github.com/styled-components/styled-components/pull/2187)~~
- [x] ~~use react v16.7+ hooks to simplify the context consumer architecture (#2390)~~
- [x] ~~babel 7 migration (maybe... there were bundle size regressions before) (#2509)~~
- [x] ~~internal rewrite to use hooks (#2390)~~
- [x] ~~bump minimum versions of react, react-native to hooks-compatible versions~~
- [x] ~~remove code paths deprecated in v4 (https://github.com/styled-components/styled-components/pull/2604)~~
- [x] ~~fix cGS style clobbering issues (https://github.com/styled-components/styled-components/pull/2824)~~

_5.1 candidate_

- [ ] stylis -> sweetsour (depending on when it's ready for use and testing)
- [ ] figure out CSP / nonce support (#2363)
- [ ] solution to drop the prop whitelist (https://github.com/styled-components/styled-components/pull/2093)
- [ ] source maps for styles (https://github.com/styled-components/styled-components/issues/827)
- [ ] scoping of styles via StyleSheetManager (https://github.com/styled-components/styled-components/issues/1789)

_didn't do_

- [ ] ~~use React.warn and React.error if 16.9 comes out before v5 (https://github.com/styled-components/styled-components/issues/2584)~~ React removed them

follow along on the ~canary~ [v5 branch](https://github.com/styled-components/styled-components/tree/v5)

_evolving_

**Comment by Andarist** [comment]
👋 From what I understand you are approaching v4 release and I would like to make a proposal for it. 
While

**Comment by Andarist** [comment]
👋 From what I understand you are approaching v4 release and I would like to make a proposal for it. 

While prop whitelist is obviously non-ideal solution and has its costs (2kb+) the approach is used by more than 1 library, it would be great if we could just use the same module for it so the cost would be one time thing. 

I'd like to propose using [is-prop-valid](https://github.com/emotion-js/emotion/tree/master/next-packages/is-prop-valid). It's obviously used by emotion, but also by popmotion since recently and I know that if we could all agree on a single module @diegohaz would love to dedupe his copied `validAttr` from reakit.

Your solution is more correct (i.e. validating post `data-` characters) but IMHO this is not really needed, the solution without that extreme correctness is "good enough" and is also slightly lighter (~0.5kb from what I remember).

**Comment by olegreznichenko** [comment]
Support browserlist/autoprefixer.
I'm tired to see prefixed styles in dev mode for flexbox.

**Comment by kitten** [comment]
@olegreznichenko As stated in multiple issues across this year and last year, styled-components does not use PostCSS anymore but stylis. So there's no configurable browserlist and even if we change our CSS processing pipeline there likely won't be any. It's not our responsibility to improve the devtools' UX afterall :wink:

**Comment by probablyup** [comment]
You'll need to propose that to stylis

**Comment by mehiel** [comment]
@probablyup Any plans to adopt react hooks? That'd make the react tree minimal! 

Maybe an `import styled from "styled-components/hooks"` in order to be able to experiment without breaking compatibility?

**Comment by probablyup** [comment]
When 16.7 comes out formally we’ll look into it. I think some core team
members have been fiddling around but the RFC isn’t finalized yet.

**Comment by Andarist** [comment]
As part of the v5 you could consider how to expose stylis for some customizations

**Comment by Carduelis** [comment]
I've seen a [lot](https://github.com/styled-components/styled-components/issues/285) [of](https://github.com/styled-components/styled-components/issues/719#issue-223054470) complainings about autoprefixes.
To conclude it in one message:
1. It is really a mess in devtools. It is hard to read, to enable or disable styles.
2. There are no sense to support some old versions of Chrome.
3. Adding new properties in runtime and applying css-rules are also an additional work for a browser.
4. There is a need to adjust browser-compatibility: someone does not support IE8-10, someone develops only for Electron or even creates pdf-generator like [this guy](https://github.com/styled-components/styled-components/issues/719#issuecomment-445112041).

**Comment by glauberfc** [comment]
Maybe add types for TypeScript on this repository itself rather than on Definitely Typed

**Comment by mxstbr** [comment]
@glauberfc as recommended by the TypeScript core team, we just moved them over from this repo to DefinitelyTyped, and we're not moving them back. See #1778 for the full discussion and information as to why.

**Comment by viiiprock** [comment]
Hooks is released today 🎉

**Comment by probablyup** [comment]
For anyone watching, the v5 branch is called "canary" and we'll be releasing alpha builds under `styled-components@canary` in the (potentially near) future.

**Comment by ShanonJackson** [comment]
Probably isn't the time or place to make a request to add something to roadmap, but the performance of styled-components more recently has been giving me a headache when i compare mounting my components with styled components vs mounting my components with css the performance is more than noticeable.

Any chance we make things faster? aswell.

**Comment by probablyup** [comment]
@ShanonJackson should be improved between the hooks refactors and stylesheet work - we'll be doing some benchmarking and optimization soon and will post results

**Comment by mxstbr** [comment]
WIP performance results: https://twitter.com/_philpl/status/1123731671507976193

**Comment by mattwills8** [comment]
@probablyup Fair enough man, thanks for your time!

**Comment by kitten** [comment]
@mattwills8 the styled-components way of doing it would be to always create a StyledComponent, so if you can create one for that div alone that'd work https://www.styled-components.com/docs/advanced#referring-to-other-components

**Comment by LennardWesterveld** [comment]
Is there a way that we can solve or making it more friendly to exclude props mapped to the component in 5.x? see for more information: https://github.com/styled-components/styled-components/issues/439

**Comment by probablyup** [comment]
@LennardWesterveld  It's the first item in the roadmap

**Comment by LennardWesterveld** [comment]
> @LennardWesterveld It's the first item in the roadmap

Oh woop! Thanks a lot :) sorry that i didn't see that.

**Comment by probablyup** [comment]
The first alphas are available under `styled-components@alpha` for those interested. See the OP for a one-liner install.

**Comment by mqklin** [comment]
This: https://github.com/styled-components/styled-components/issues/2215
Still on v3, because v4 is unusable in dev mode :(

**Comment by probablyup** [comment]
Definitely addressed in v5, have you tried the beta?

**Comment by mqklin** [comment]
Not yet, does it have incompatibilities with v4? Is there any migrate guide from v4 to v5? I ask because our project is pretty big, so it can take time to migrate

**Comment by mxstbr** [comment]
No breaking changes from v4 to v5, see the announcement blogpost: https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987

**Comment by Jessidhia** [comment]
There's one minor change I noticed, but it's on code that had been incorrectly ported to begin with: the new stylis seems to have changed how it treats the `:global()` pseudo-class.

It's not necessary in styled-components code anyway so the `:global()`s shouldn't have been there, but I just found it interesting 🤔

**Comment by mxstbr** [comment]
We should definitely not allow usage of `:global()`, not sure why we were allowing that before! The new stylis has all features removed that don't make sense in styled-components in order to slim the bundle size, including `:global()`.

**Comment by Jessidhia** [comment]
I'm not sure exactly what was going on, but given this (incorrectly ported) selector `:global(.trident) &`, old `stylis` would produce `:global(.trident) .c1` in the snapshot; while the new `@emotion/stylis` produces `.c2:global(.trident) .c3`.

The `:global(.trident)` was broken anyway, it should have never stayed as `:global()` and, given how it was showing up in the snapshot, it never worked. Luckily thanks to this mostly inconsequential change I noticed a bug 🤣

**Comment by mqklin** [comment]
I've just migrated from v3 to v5@beta, and it's fast! Cool! Thanks guys, you are the beasts!

**Comment by mqklin** [comment]
Could you please explain what happens if I render `createGlobalStyle` component several times inside some component, and not at the top of your React tree? For example:
```
const GlobalStyle = createGlobalStyle`
  #some-external-lib-element {
    color: red;
  }
`;
function Button({veryOftenChangingPropThatCausesRerender}) {
  return (
    <>
      <GlobalStyle/>
      <SomeExternalLibComponent/>
    </>
  );
}
```

Will it insert global style several times, or will it clear it after every unmount? 
I ask here because I couldn't find this info in the docs, and maybe you will add this to the roadmap? :)

**Comment by probablyup** [comment]
@mqklin let's keep this issue focused on v5 please. Stack Overflow or our Spectrum community is a great place to ask general usage questions.

**Comment by corysimmons** [comment]
Can the styled-components team please release/maintain a super official NextJS example for v5?

NextJS is most popular(?) SSR framework out there and it'd probably help a _ton_ of people—obviously including myself—if smooth integration with it was more of a priority.

That is, the only reason I use Emotion and will probably continue to use Emotion is because getting it working with SSR is as easy as `yarn add emotion babel-plugin-emotion; // import styled from '@emotion/styled'`

Like... honestly compare these:

- [NextJS with-styled-components](https://github.com/zeit/next.js/tree/564eac47462cf65cd80c140dff72160845e4e4de/examples/with-styled-components) | [_document.js 🤢](https://github.com/zeit/next.js/blob/564eac47462cf65cd80c140dff72160845e4e4de/examples/with-styled-components/pages/_document.js)
- [NextJS with-emotion](https://github.com/zeit/next.js/tree/564eac47462cf65cd80c140dff72160845e4e4de/examples/with-emotion) 😍

SSR is huge nowadays. You beat them to Hooks and a beautiful DevTools experience, but **IMO** the winning library will be the first to get both a decent DevTools experience (no `Context.Consumer` pollution) + nice SSR. 🤷‍♂️

**Comment by probablyup** [comment]
what’s wrong with the current one you linked? It’s what I use for my own
nextjs projects and works fine...

**Comment by corysimmons** [comment]
tbh I was getting some Hooks problems with it and some classes not matching up between client/server. Been fighting with NextJS + styled-components@beta for a couple days and then went back to Emotion and it worked perfectly. So I don't know if I'm stupid and should fully understand what is going on in `_app.js` and `_document.js`, or if styled-components doesn't have as intuitive SSR support as Emotion. Maybe both, but a roadmap isn't really the place for tech support so much as wishlisting things.

So again, I wish styled-components had really simple/slick/easy SSR support (whether by some babel plugin that just obfuscates all this stuff or some other way), like Emotion does.

**Comment by corysimmons** [comment]
_"Please give stronger consideration to elegant SSR support before pushing 5"_  is off-topic for the 5 roadmap issue?

**Comment by probablyup** [comment]
@corysimmons yes because a stated goal of this release is backward compat with v4

**Comment by oliviertassinari** [comment]
@corysimmons How does Emotion handle CSS specificity issues with third-parties when injecting the style elements in the body?

**Comment by probablyup** [comment]
@oliviertassinari off-topic, please guys

**Comment by leantide** [comment]
v5 looking great. Sorry if I should know this, but did any solution make it into v5 for keeping styling-only props from being applied to the DOM node? Thanks.

**Comment by davidcsally** [comment]
I noticed that with v5, you can have multiple applications running styled-components on the page now. This wasn't possible in v4.

**Comment by probablyup** [comment]
@davidcsally actually it is possible in v4, just specifically with different versions of the lib because we add a version attribute to the style tags that allows for isolation

**Comment by felipeleusin** [comment]
Just wanted to say thanks for this! I onboarded a new dev that wasn't familiarized to styled-components but was too react and he was complaining about the react devtools clutter until I showed him what v5 looked like.

Also for our applications adopting v5 beta happened without issues

**Comment by anmolmahatpurkar** [comment]
Any updates on the eta for the 5.0 launch?

**Comment by khryshyn** [comment]
Please update type deffinitions for version 5 in DefinitelyTyped/types/styled-components, because now there only deffinitions for v4

**Comment by riongull** [comment]
Anyone know if it's possible to use the 5.0 beta version with Gatsby?  I just replaced my version 4 with it and am now getting npm warnings:

```
npm WARN babel-plugin-styled-components@1.10.6 requires a peer of styled-components@>= 2 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-styled-components@3.1.2 requires a peer of styled-components@>=2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylis-rule-sheet@0.0.10 requires a peer of stylis@^3.5.0 but none is installed. You must install peer dependencies yourself.
```
I'm a new enough developer to not not know if these warnings are related to upgrading to 5.0, if they can be ignored, and how to address them if related and can't be ignored.  Do I just need to `npm install` those peer dependencies?  If so, as normal, or as dev dependencies?  

My Gatsby app (now using 5.0) is still working except for:

1. The styled-components' class names are not prefixed with my component names anymore.  Is this related to `babel-plugin-styled-components` being mad (npm warning above)?
2. I lost some locally hosted fonts and a few links are styled differently for some reason. Any reason that would be?  Has anything changed regarding how styles and classes are injected into the DOM?
 
Thanks in advance for any help.

**Comment by dorshinar** [comment]
@riongull I'm running Gatsby with styled-components@5.0 with no issues at all. You can take a look here - https://github.com/dorshinar/blog/blob/master/package.json

**Comment by lcswillems** [comment]
Is it possible to include this very short code somewhere in the library?

```
import { useContext } from 'react';
import { ThemeContext } from 'styled-components';

export const useTheme = () => useContext(ThemeContext);
```

Hence, it will be sufficient to do:
```
import {useTheme} from 'styled-components';

const theme = useTheme();
```
to get the theme.

Thank you for all your work.

**Comment by semoal** [comment]
__

> Is it possible to include this very short code somewhere in the library?
> 
> ```
> import { useContext } from 'react';
> import { ThemeContext } from 'styled-components';
> 
> export const useTheme = () => useContext(ThemeContext);
> ```
> 
> Hence, it will be sufficient to do:
> 
> ```
> import { useTheme } from 'styled-components';
> 
> const theme = useTheme();
> ```
> 
> to get the theme.
> 
> Thank you for all your work.

Nice idea! I've tried to add it. #2765

**Comment by melloc01** [comment]
Hi guys, what is needed for the 5.0 release? It seems that #1789 will be postponed to 5.1?

**Comment by Can-Sahin** [comment]
Check out to see if `5.0` is released. I will let you know 😁

https://can-sahin.github.io/Is-Styled-Components-Released/ 

(Made it for fun. Love styled-components)

**Comment by jacobp100** [comment]
@probablyup could we add #2782 (update css-to-react-native) to this? 😄

**Comment by jacobp100** [comment]
@probablyup Hey, sorry, I tried to set up this repo, but it fails on trying to install the packages via `yarn`

I've published css-to-react-native 3.0.0

If someone is able to run `yarn upgrade-interactive --latest` and update that package, that'd help me a lot

Thanks!

**Comment by joshjg** [comment]
Opened this issue to track the typescript definition changes that are needed.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39450

**Comment by sidletsky** [comment]
When is the release of v.5?

**Comment by mxstbr** [comment]
Hopefully soon @sidletsky, we already have our first release candidate out! 👍

**Comment by viiiprock** [comment]
any idea to resolve this https://github.com/styled-components/styled-components/issues/439
in v5?

**Comment by anmolmahatpurkar** [comment]
The project seems to be quite inactive for a while. Should there be any concerns for future support?

**Comment by probablyup** [comment]
@anmolmahatpurkar it's not inactive, look at the v5 PR

**Comment by anmolmahatpurkar** [comment]
Oh, my apologies. Last visited this thread in july. Thought we were close to launch in July. Seeing that v5 is not launched yet made me wonder.

However, glad to know we are still active :)

**Comment by probablyup** [comment]
https://github.com/styled-components/styled-components/releases/tag/v5.0.0 :shipit:

**Comment by fabb** [comment]
@probablyup could you please add something like this to the release notes, it took us quite some time to find out this breaking change in v5, and others might benefit from it as well:

Note: In SSR projects it now is necessary that global styles need to be collectable like regular styles. In the case of next.js, it is no longer possible to put them into the render function of the `_document.js`. To fix this, move them to `_app.js` or some other component in the render tree below.

**Comment by probablyup** [comment]
I don’t think that’s ever been recommended or documented?

**Comment by fabb** [comment]
It also hasn‘t been discouraged, and it used to work fine in v4.

**Comment by fabb** [comment]
Released v5 to production today, looks great! Slightly lower SSR memory usage and render times.
